### ISSUE TITLE
请问GeneratorTest的URL从哪里获取呢

### ISSUE THREAD

**Issue by mayubin258** [JesseTzh/stable-diffusion-java#6]
再GeneratorTest类的URL属性，代码完整下下来后发现是https://xxxxxxxxxxxxx.gradio.live/，找了挺久没找到

**Comment by JesseTzh** [comment]
就是 stable-diffusion 后台接口，代码中仅做示例。
如果使用 [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) 部署的话，在最后会提供一个这样的链接
